### ISSUE TITLE
请问训练的数据集如何获取啊？

### ISSUE THREAD

**Issue by p-moon** [shibing624/textgen#12]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
哪个任务的训练集？
一般训练样本集来源于：
1. 开源比赛会提供；
2. 自己业务积累收集；
3. 标注员人工撰写。

**Comment by p-moon** [comment]
我看一共就两个功能，一个是对对联，一个是文章生成，因为我最近正在学习相关的内容，代码也大概看了，但是手头没有相关的样本集，请问您这边用于训练的数据集可以共享一下嘛？

**Comment by shibing624** [comment]
数据共享了的：https://github.com/shibing624/textgen/blob/main/docs/%E5%AF%B9%E8%81%94%E7%94%9F%E6%88%90%E6%A8%A1%E5%9E%8B%E5%AF%B9%E6%AF%94.md  

https://github.com/shibing624/textgen/blob/main/docs/%E5%8F%A4%E8%AF%97%E7%94%9F%E6%88%90%E6%A8%A1%E5%9E%8B%E5%AF%B9%E6%AF%94.md

**Comment by p-moon** [comment]
好的好的，感谢大佬，我看一下，感激不尽
