### ISSUE TITLE
如何用使用 p40 训练lora

### ISSUE THREAD

**Issue by hongyix** [shibing624/textgen#21]
### Describe the bug
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised RuntimeError: Found Tesla P40 which is too old to be supported by the triton GPU compiler, which is used as the backend. Triton only supports devices of CUDA Capability >= 7.0, but your device is of CUDA capability 6.1

### To Reproduce
![image](https://user-images.githubusercontent.com/14794327/233533282-0a0d4a90-d336-4860-9d96-d0373c1a5ede.png)

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

按照https://www.reddit.com/r/StableDiffusion/comments/12nh9hn/dreambooth_training_lora_failed_due_to_triton_gpu/ 上说的配置export TORCHDYNAMO_DISABLE=1 
重跑后会报

RuntimeError: GET was unable to find an engine to execute this computation

### Context
 - **OS** [CentOS Linux]: 
 - **Hardware** [Tesla P40]:

**Comment by shibing624** [comment]
升级cuda

**Comment by xiongxiaochu** [comment]
> 升级cuda

现在的cuda版本是11.4，但是报错提示的是P40的算力低于7.0，请问下P40是不是不能跑lora呀？

**Comment by hongyix** [comment]
升级cuda和最新版本的peft就可以了。
