### ISSUE TITLE
用lora训练chatglm时跑内存

### ISSUE THREAD

**Issue by NefelibataJay** [shibing624/textgen#29]
下午我在跑的时候就爆过一次内存，当时没在意，但是刚刚看的时候注意到按道理这个模型应该只占14g多，现在跑到第二个epoch的时候就莫名内存占用变大了。
![image](https://github.com/shibing624/textgen/assets/76277451/0f892bdd-55d8-4c6e-9730-c1d5490a06ac)
这是跑到第三个epoch时的内存占用
![image](https://github.com/shibing624/textgen/assets/76277451/d844fc7d-ea23-4f0e-ab4d-a5812eb360bd)

**Comment by NefelibataJay** [comment]
![image](https://github.com/shibing624/textgen/assets/76277451/d1931724-2882-413d-abf3-4fac1ec94e00)
回退到之前的版本正常了

**Comment by NefelibataJay** [comment]
应该是每轮跑完cuda的缓存没有清理干净

**Comment by NefelibataJay** [comment]
我不确定是否是这个原因（按道理来说应该不是），但是这样试过后确实是解决了。
我之前的安装方式时候`pip install -e ./`。今天下午把textgen卸载了`pip uninstall textgen`，直接使用原本的`python setup.py install`安装后，完美解决。

**Comment by shibing624** [comment]
好吧
