### ISSUE TITLE
pip安装最新版v0.1.2时发现textgen文件夹下缺少data文件夹

### ISSUE THREAD

**Issue by bingxin3chen** [shibing624/textgen#3]
### Describe the bug
@shibing624 
徐老师您好， pip3 install -U textgen 安装 textgen后，版本确实显示是最新版本v0.1.2，但 textgen文件夹下缺少了data文件夹。
![image](https://user-images.githubusercontent.com/89672905/182802871-d1de395b-c196-4fd0-ac93-65de7a214b53.png)

![image](https://user-images.githubusercontent.com/89672905/182801082-a341fdb3-36eb-42e1-8459-5abb42ee8c94.png)
github中界面：
![image](https://user-images.githubusercontent.com/89672905/182802026-90fed0ba-c056-4939-a533-bf7952ee8122.png)

因此在运行 examples/unsup_generation_demo.py 文件时就会报如下错误：
![image](https://user-images.githubusercontent.com/89672905/182800843-cde28078-8f12-4ca5-96e4-485e8453382b.png)

**Comment by shibing624** [comment]
fixed. https://github.com/shibing624/textgen/commit/40d5544fead05a400e351f11bbebaa2c7b3189fa
