### ISSUE TITLE
保存模型问题

### ISSUE THREAD

**Issue by MonkeyTB** [shibing624/textgen#33]
想请教一下，这种保存模型除了 adapter_model.bin 和 adapter_config.json ，其他文件是否都与lora 无关？
如果想像原始6b那种流式输出的时候，这里应该怎么改？有好的建议嘛

**Comment by shibing624** [comment]
1. 是；
2. 把它流式预测的方法抄来用下就行，本质就是yield 输出就行。

**Comment by MonkeyTB** [comment]
> 

谢谢，我试试，感谢
