### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by LMXKO** [shibing624/textgen#36]
在SFT的模型训练中，报错如下：
![image](https://github.com/shibing624/textgen/assets/35209678/2e1a42b7-f2bc-433b-b9c4-e1ca927f205e)

**Comment by shibing624** [comment]
哪个模型，哪个数据，哪个调用脚本出错？

**Comment by LMXKO** [comment]
> 
模型：chinese-llama-plus-7b-merged
数据：medical
代码块：
![image](https://github.com/shibing624/textgen/assets/35209678/fce907ba-0a74-444f-89d6-d52ac3fc3db8)

**Comment by LMXKO** [comment]
> 哪个模型，哪个数据，哪个调用脚本出错？

好像找到了，跟这个一样
https://github.com/THUDM/ChatGLM-6B/issues/530
