### ISSUE TITLE
我想让TGLS精简些，但一改就会报错

### ISSUE THREAD

**Issue by Ocyss** [shibing624/textgen#4]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [x] I walked through the tutorials
- [x] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question
![image](https://user-images.githubusercontent.com/68412205/187574170-ce719d05-1818-47d1-855c-516f5d6eab70.png)
我这个报错是因为给点数据太少了么？？？

**Comment by shibing624** [comment]
1、是想改动TGLS源码吗？如果改源码，先卸载`pip unistall textgen`，用改动后的代码运行。
2、如果只是小批量数据测试，需要满足generate(doc)的doc size>100，才能生成有质量的仿写句子。 fixed with keyerror: https://github.com/shibing624/textgen/commit/10e03bea14144599d4a9953e810ad1dc3da0f399
