### ISSUE TITLE
README中LLaMA模型部分是不是还没有更新+merge_peft_adapter.py的save_pretrained()似乎有问题

### ISSUE THREAD

**Issue by PolarisRisingWar** [shibing624/textgen#46]
我看好像LLaMA模型从llamamodel换成gptmodel了？

一个是LLaMA的代码示例，还有一个模型转换部分，我是直接用Python执行实现的：
```bash
python whj_download/githubs/textgen/textgen/gpt/merge_peft_adapter.py \
    --base_model_name_or_path /data/whj/pretrained_model/llama-7b/llama \
    --peft_model_path /data/whj/pretrained_model/chinese-alpaca-lora-7b \
    --output_type huggingface \
    --output_dir /data/whj/pretrained_model/chinese-alpaca-plus-7b-hf \
    --offload_dir /data/whj/cache
```
whj_download/githubs/textgen/textgen/gpt/merge_peft_adapter.py这个代码原303行`AutoModelForCausalLM.save_pretrained(base_model, output_dir)`这个是否是transformers版本的问题？我是transformers 4.30.2，需要改成`base_model.save_pretrained(output_dir)`才能运行，否则会报`AttributeError: type object 'AutoModelForCausalLM' has no attribute 'save_pretrained'`错

**Comment by shibing624** [comment]
嗯，我更新下。
