### ISSUE TITLE
数据集格式

### ISSUE THREAD

**Issue by westwet** [shibing624/textgen#5]
想请问一下您bart的数据集应该处理成哪种形式呢

**Comment by shibing624** [comment]
正常seq2seq的数据格式就行。样本如： https://github.com/shibing624/textgen/blob/main/examples/data/zh_couplet_test.tsv

**Comment by westwet** [comment]
> 正常seq2seq的数据格式就行。样本如： https://github.com/shibing624/textgen/blob/main/examples/data/zh_couplet_test.tsv

好的我试一下，感谢！！
