### ISSUE TITLE
大佬请问有没有针对chatglm3的评估脚本呀

### ISSUE THREAD

**Issue by Franklin-L** [shibing624/textgen#58]
前辈您好，我是小白接触chatglm3，最近在想办法评估微调后的chatglm3的性能，现在是了解到对于通用的评估有BLEU 和 ROUGE 分数，请问前辈做过这个方面的吗

**Comment by shibing624** [comment]
用cEval, MMLU

**Comment by Franklin-L** [comment]
嗷嗷好的谢谢大佬，那针对微调后的呢，如果想自己个性化定制一个方法应该怎么下手呢

**Comment by shibing624** [comment]
微调后评估。
