### ISSUE TITLE
您好，请教一下语法纠错后的PRF如何计算？

### ISSUE THREAD

**Issue by ImXunan** [shibing624/textgen#8]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [x] I walked through the tutorials
- [x] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
1、语法纠错问题请到纠错repo提问；
2、计算方法参考：https://github.com/shibing624/pycorrector/blob/master/pycorrector/utils/eval.py#L324
