### ISSUE TITLE
输入关键词 去生成关键词相关的文章用GPT2合适吗？

### ISSUE THREAD

**Issue by huyi1989** [shibing624/textgen#9]
还有这种类型的训练数据格式具体是咋样的？  直接关键词对应文章吗？

**Comment by huyi1989** [comment]
我用demo脚本做预测的时候，提示缺少文件  FileNotFoundError: [Errno 2] No such file or directory: './outputs/convseq2seq_zh/src_vocab.txt'  请问这个是什么字典文件？

**Comment by huyi1989** [comment]
![1667969973215](https://user-images.githubusercontent.com/25134357/200742773-6c0931bd-7328-4f69-a722-981bb748fd9b.png)

**Comment by shibing624** [comment]
哪个demo？更新下代码再看看吧，一般需要先训练，训练后会生成vocab文件。

**Comment by huyi1989** [comment]
好的 感谢  那请问怎么选择预训练模型和分词器呢？ 这个训练是重头开始的还是加载了transformers的模型进行微调的？

**Comment by shibing624** [comment]
gpt2是基于预训练模型的；convseq2seq不需要预训练模型。
